
INSERT INTO SUBSCRIPTIONS (ID, CURRENCY_PAIR, USER_NAME, THRESHOLD) VALUES (1000, 'BTC-USD', 'admin', 3000);
INSERT INTO SUBSCRIPTIONS (ID, CURRENCY_PAIR, USER_NAME, THRESHOLD) VALUES (2000, 'BTC-EUR', 'user1', 4000);
INSERT INTO SUBSCRIPTIONS (ID, CURRENCY_PAIR, USER_NAME, THRESHOLD) VALUES (3000, 'BTC-TRY', 'admin', 3000);
INSERT INTO SUBSCRIPTIONS (ID, CURRENCY_PAIR, USER_NAME, THRESHOLD) VALUES (4000, 'BTC-PLN', 'user2', 2000);
INSERT INTO SUBSCRIPTIONS (ID, CURRENCY_PAIR, USER_NAME, THRESHOLD) VALUES (5000, 'BTC-USD', 'user2', 3000);
INSERT INTO SUBSCRIPTIONS (ID, CURRENCY_PAIR, USER_NAME, THRESHOLD) VALUES (6000, 'BTC-USD', 'user1', 3000);